[project]
name = "Stereochemical-Assesments"
version = "0.1.0"
description = "Add a short description here"
authors = ["Vedh Kannan <vedhkannan@gmail.com>", "Sibbe Bakker <sibbe.l.bakker@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
biopython = ">=1.84,<2"
matplotlib = ">=3.9.1,<3.10"
numpy = ">=2.0.0,<2.1"

[system-requirements]
linux="4.12.14"
